---
title: "PRS"
output: html_document
date: "2025-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(dplyr)
library(glue)
library(stringr)
library(ggplot2)
```

```{r}
trait <- "PGS002804"
PGSfile <- glue("R:/Doktoranden/MarieFreudenberg/analysen/LIFE_PRS/{trait}_scorefile.txt")
```

# use scorefile created for LIFE Adult and remove 'chr' in front of SNP ID
```{r}
scorefile <- read_table(PGSfile)
scorefile <- scorefile %>%
  mutate(SNP = str_remove(SNP, "^chr"))
```

```{r}
write_tsv(scorefile, glue("R:/Doktoranden/MarieFreudenberg/analysen/1kGp3_PRS/{trait}_scorefile.tsv"))
```


# Calculate PRS for the trait using PLINK2
```{r}
system(glue("C:/Users/mar5862fre/Downloads/plink2_win64_20251026/plink2.exe --pfile R:/Doktoranden/MarieFreudenberg/daten/1kG_ph3/1kgALL_ph3_hg38_maf001_uniqueSNPIDs --score R:/Doktoranden/MarieFreudenberg/analysen/1kGp3_PRS/{trait}_scorefile.tsv 1 2 3 header cols=+scoresums --out R:/Doktoranden/MarieFreudenberg/analysen/1kGp3_PRS/{trait}_PRS_output"))
```
```{r}
prs <- read_table(glue("R:/Doktoranden/MarieFreudenberg/analysen/1kGp3_PRS/{trait}_PRS_output.sscore"))
```

#Compare PRS of Populations and SuperPops
```{r}
prs %>%
  group_by(SuperPop) %>%
  summarise(mean_score = mean(SCORE1_SUM), .groups = "drop")
```
```{r}
prs %>%
  group_by(Population) %>%
  summarise(mean_score = mean(SCORE1_SUM), .groups = "drop")
```
```{r}
# Create an ordering of populations by SuperPop
pop_order <- prs %>%
  distinct(SuperPop, Population) %>%
  arrange(SuperPop, Population) %>%
  pull(Population)

# Apply the ordering to the factor
prs <- prs %>%
  mutate(Population = factor(Population, levels = pop_order))

#Plot
ggplot(prs, aes(x = Population, y = SCORE1_SUM, fill = SuperPop)) +
  geom_boxplot(outlier.shape = NA) +
  theme_minimal() +
  labs(title = "PRS by Population",
       x = "Population",
       y = glue("{trait} PRS")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

#Standardize the scores and add a new column to the file
```{r}
prs$SCORE_standardized <- scale(prs$SCORE1_SUM)
```

#Plot the standardized scores 
```{r}
# Create an ordering of populations by SuperPop
pop_order <- prs %>%
  distinct(SuperPop, Population) %>%
  arrange(SuperPop, Population) %>%
  pull(Population)

# Apply the ordering to the factor
prs <- prs %>%
  mutate(Population = factor(Population, levels = pop_order))

#Plot
ggplot(prs, aes(x = Population, y = SCORE_standardized, fill = SuperPop)) +
  geom_boxplot(outlier.shape = NA) +
  theme_minimal() +
  labs(x = "Population",
       y = glue("{trait}")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
